version: '2'
services:
  app:
    image: node-web-server:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      MONGODB_URL: db
      MONGODB_PORT: 27017
    depends_on:
      - db
    networks:
      - bridge-network
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - bridge-network
networks:
    bridge-network:
     driver: bridge
